name: Build and upload the artifact
on: 
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build IPA
        run: |
          cd ${{GITHUB.WORKSPACE}}
          ./ipabuild.sh

      - name: Upload artifak
        uses: actions/upload-artifact@v4
        with:
          name: dirtyZero
          path: 
          retention-days: 90
          
